prompt --application/pages/page_00008
begin
--   Manifest
--     PAGE: 00008
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>16769126531911660025
,p_default_application_id=>118394
,p_default_id_offset=>0
,p_default_owner=>'WKSP_QUACKER'
);
wwv_flow_api.create_page(
 p_id=>8
,p_user_interface_id=>wwv_flow_api.id(17252290821906312400)
,p_name=>'Strain Graph'
,p_alias=>'STRAIN-GRAPH'
,p_step_title=>'Strain Graph'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_last_updated_by=>'SALTYQUACKER.GAMES@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20220111165042'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19064579601272758203)
,p_plug_name=>'Pre-Rolls - Last 7 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>60
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19064579793053758204)
,p_region_id=>wwv_flow_api.id(19064579601272758203)
,p_chart_type=>'line'
,p_title=>'Pre-Rolls By Strain (Weekly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'auto'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126180478671205131)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>20
,p_name=>'Total Pre-Roll Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064579899810758205)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>40
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580136726758208)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>50
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580205471758209)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>60
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7)GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580333731758210)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>70
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT , TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580455166758211)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>80
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580516705758212)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>90
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580645398758213)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>100
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#a63b0a'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126179332752205120)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>110
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(22480252061786454601)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_seq=>120
,p_name=>'Lemon Cheese'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Lemon Cheese'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f8fa7c'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064579917319758206)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064580072204758207)
,p_chart_id=>wwv_flow_api.id(19064579793053758204)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19064580799294758214)
,p_plug_name=>'Flower (3.5g) - Last 7 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>80
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19064580839204758215)
,p_region_id=>wwv_flow_api.id(19064580799294758214)
,p_chart_type=>'line'
,p_title=>'Flower (3.5g) by Strain (Weekly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126180697809205133)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>20
,p_name=>'Total Flower (3.5g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON''AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064580962394758216)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>40
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581011053758217)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>50
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581171071758218)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>60
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7)GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581274013758219)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>70
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581316825758220)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>80
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581411918758221)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>90
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064581536667758222)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>100
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#a63b0a'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126179485419205121)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>110
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7)  GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(22480252104490454602)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_seq=>120
,p_name=>'Lemon Cheese'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Lemon Cheese'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f8fa7c'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064581687250758223)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064581707681758224)
,p_chart_id=>wwv_flow_api.id(19064580839204758215)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19064581852447758225)
,p_plug_name=>'Flower (7g) - Last 7 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>100
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19064581903846758226)
,p_region_id=>wwv_flow_api.id(19064581852447758225)
,p_chart_type=>'line'
,p_title=>'Flower (7g) By Strain (Weekly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126180874866205135)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>10
,p_name=>'Total Flower (7g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON''AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582073876758227)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582166632758228)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>40
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582207887758229)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>50
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582333870758230)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>60
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582405118758231)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>70
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582521932758232)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>80
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064582629326758233)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>90
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126179516901205122)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_seq=>100
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064582824667758235)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064582701529758234)
,p_chart_id=>wwv_flow_api.id(19064581903846758226)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19064582971203758236)
,p_plug_name=>'Vaporizers (0.5g) - Last 7 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>120
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19064583017895758237)
,p_region_id=>wwv_flow_api.id(19064582971203758236)
,p_chart_type=>'line'
,p_title=>'Vaporizers (0.5g) By Strain (Weekly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126180980136205136)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>10
,p_name=>'Total Vaporizer (0.5g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE ,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583102701758238)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE, WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583290662758239)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>40
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), WEIGHT, TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DAT'
||'E_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583355514758240)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>50
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>16769126531911660025
,p_default_application_id=>118394
,p_default_id_offset=>0
,p_default_owner=>'WKSP_QUACKER'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583401406758241)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>60
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583502001758242)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>70
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583615084758243)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>80
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-7) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064583706871758244)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>90
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Vaporizers'' AND DATE_>=trunc(SYSDATE-7) AND WEIGHT=''0.5g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126179617051205123)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_seq=>100
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Vaporizers'' AND DATE_>=trunc(SYSDATE-7) AND WEIGHT=''0.5g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064583828239758245)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19064583945465758246)
,p_chart_id=>wwv_flow_api.id(19064583017895758237)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19064584090920758247)
,p_plug_name=>'Concentrate  - N/A'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>150
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19064584137092758248)
,p_region_id=>wwv_flow_api.id(19064584090920758247)
,p_chart_type=>'line'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181092835205137)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>10
,p_name=>'Total Concentrate Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Concentrate'' GROUP BY DATE_,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffffff'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064584255175758249)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19064584357667758250)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>40
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126177420314205101)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>50
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126177589897205102)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>60
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126177676810205103)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>70
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126177732257205104)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>80
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126177856025205105)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>90
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126179708891205124)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_seq=>100
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Concentrate'' GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19126178098838205107)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19126177995984205106)
,p_chart_id=>wwv_flow_api.id(19064584137092758248)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(19126181196913205138)
,p_plug_name=>'Vaporizers (1.0g) - N/A'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>140
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(19126181214945205139)
,p_region_id=>wwv_flow_api.id(19126181196913205138)
,p_chart_type=>'line'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_legend_font_color=>'#888888'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181396909205140)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>10
,p_name=>'Total Vaporizer (1.0g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181440056205141)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181554753205142)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>30
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Vaporizers'' AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181641237205143)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>40
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181761784205144)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>50
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181852976205145)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>60
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126181941216205146)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>70
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Vaporizers''  AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126182084372205147)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>80
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Vaporizers'' AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(19126182169970205148)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_seq=>90
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Vaporizers'' AND WEIGHT=''1.0g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19126182389263205150)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(19126182202272205149)
,p_chart_id=>wwv_flow_api.id(19126181214945205139)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(26260085885600534213)
,p_plug_name=>'Pre-Rolls - Last 30 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>70
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(26260085938468534214)
,p_region_id=>wwv_flow_api.id(26260085885600534213)
,p_chart_type=>'line'
,p_title=>'Pre-Rolls By Strain (Monthly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'auto'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086003327534215)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>10
,p_name=>'Total Pre-Roll Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'afterMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086150541534216)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086234488534217)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>30
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086338412534218)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>40
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30)GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086473452534219)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>50
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT , TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086529953534220)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>60
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086644762534221)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>70
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086724904534222)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>80
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#a63b0a'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086834425534223)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>90
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260086934089534224)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_seq=>100
,p_name=>'Lemon Cheese'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Lemon Cheese'' AND TYPE=''Pre-Rolls'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT, TYPE ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f8fa7c'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26260087070055534225)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26260087164384534226)
,p_chart_id=>wwv_flow_api.id(26260085938468534214)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(26260087522733534230)
,p_plug_name=>'Flower (3.5g) - Last 30 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>90
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(26260087610396534231)
,p_region_id=>wwv_flow_api.id(26260087522733534230)
,p_chart_type=>'line'
,p_title=>'Flower (3.5g) by Strain (Monthly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260087790749534232)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>10
,p_name=>'Total Flower (3.5g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON''AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.component_end;
end;
/
begin
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.0'
,p_default_workspace_id=>16769126531911660025
,p_default_application_id=>118394
,p_default_id_offset=>0
,p_default_owner=>'WKSP_QUACKER'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260087887123534233)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260087941295534234)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>30
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088008219534235)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>40
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30)GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088159178534236)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>50
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088296405534237)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>60
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088367942534238)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>70
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088425550534239)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>80
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#a63b0a'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088524688534240)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>90
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30)  GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260088632547534241)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_seq=>100
,p_name=>'Lemon Cheese'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Lemon Cheese'' AND TYPE=''Flower'' AND WEIGHT=''3.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f8fa7c'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26260088713808534242)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26260088833613534243)
,p_chart_id=>wwv_flow_api.id(26260087610396534231)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(26260088970208534244)
,p_plug_name=>'Flower (7g) - Last 30 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>110
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(26260089084848534245)
,p_region_id=>wwv_flow_api.id(26260088970208534244)
,p_chart_type=>'line'
,p_title=>'Flower (7g) By Strain (Monthly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260089139532534246)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>10
,p_name=>'Total Flower (7g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON''AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260089298160534247)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260089396026534248)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>30
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260089444603534249)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>40
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26260089542359534250)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>50
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542921321980968201)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>60
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542921425515968202)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>70
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542921502051968203)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>80
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542921682429968204)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_seq=>90
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Flower'' AND WEIGHT=''7g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, PRODUCT,TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26542921726250968205)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26542921887039968206)
,p_chart_id=>wwv_flow_api.id(26260089084848534245)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(26542921968889968207)
,p_plug_name=>'Vaporizers (0.5g) - Last 30 days'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_escape_on_http_output=>'Y'
,p_plug_template=>wwv_flow_api.id(17252140355560312356)
,p_plug_display_sequence=>130
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>'SELECT DATE_, PRODUCT,COUNT(PRODUCT) FROM JCPRODUCTS WHERE PROVINCE = ''ON'' GROUP BY DATE_, PRODUCT '
,p_plug_source_type=>'NATIVE_JET_CHART'
,p_plug_query_num_rows=>15
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_jet_chart(
 p_id=>wwv_flow_api.id(26542922008878968208)
,p_region_id=>wwv_flow_api.id(26542921968889968207)
,p_chart_type=>'line'
,p_title=>'Vaporizers (0.5g) By Strain (Monthly)'
,p_height=>'500'
,p_animation_on_display=>'auto'
,p_animation_on_data_change=>'auto'
,p_orientation=>'vertical'
,p_data_cursor=>'on'
,p_data_cursor_behavior=>'auto'
,p_hide_and_show_behavior=>'withRescale'
,p_hover_behavior=>'dim'
,p_stack=>'off'
,p_connect_nulls=>'Y'
,p_sorting=>'label-asc'
,p_fill_multi_series_gaps=>true
,p_zoom_and_scroll=>'off'
,p_tooltip_rendered=>'Y'
,p_show_series_name=>true
,p_show_group_name=>true
,p_show_value=>true
,p_legend_rendered=>'on'
,p_legend_title=>'Strains'
,p_legend_position=>'auto'
,p_legend_font_size=>'14'
,p_time_axis_type=>'enabled'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922131610968209)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>10
,p_name=>'Total Vaporizer (0.5g) Units'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, SUM(CURRENTSTOCK), TYPE ,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#000000'
,p_line_style=>'dashed'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>true
,p_items_label_position=>'aboveMarker'
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922274324968210)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>20
,p_name=>'Acapulco Gold'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE, WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Acapulco Gold'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#f6c429'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922342300968211)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>30
,p_name=>'French Macaron'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), WEIGHT, TYPE FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''French'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DA'
||'TE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#eb8cfe'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922430827968212)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>40
,p_name=>'Blueberry Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Blueberry Kush'' AND TYPE=''Vaporizers'' AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7ca4fa'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922517300968213)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>50
,p_name=>'Unicorn Poop'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Unicorn Poop'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30)GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#7f50ff'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922629351968214)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>60
,p_name=>'Cherry Bomb'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Cherry Bomb'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ff9e89'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922728428968215)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>70
,p_name=>'Pyramid'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Pyramid'' AND TYPE=''Vaporizers''  AND WEIGHT=''0.5g'' AND DATE_>=trunc(SYSDATE-30) GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#8fffb6'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922872703968216)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>80
,p_name=>'Critical Kush'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Critical Kush'' AND TYPE=''Vaporizers'' AND DATE_>=trunc(SYSDATE-30) AND WEIGHT=''0.5g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#462a10'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_series(
 p_id=>wwv_flow_api.id(26542922926749968217)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_seq=>90
,p_name=>'Tang Breath'
,p_data_source_type=>'SQL'
,p_data_source=>'SELECT DATE_, PRODUCT,SUM(CURRENTSTOCK), TYPE,WEIGHT FROM JCPRODUCTS WHERE PROVINCE = ''ON'' AND PRODUCT = ''Tang Breath'' AND TYPE=''Vaporizers'' AND DATE_>=trunc(SYSDATE-30) AND WEIGHT=''0.5g'' GROUP BY DATE_, TYPE,WEIGHT,PRODUCT ORDER BY DATE_ ASC'
,p_items_value_column_name=>'SUM(CURRENTSTOCK)'
,p_items_label_column_name=>'DATE_'
,p_color=>'#ffac12'
,p_line_style=>'solid'
,p_line_type=>'auto'
,p_marker_rendered=>'auto'
,p_marker_shape=>'auto'
,p_assigned_to_y2=>'off'
,p_items_label_rendered=>false
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26542923061719968218)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_axis=>'x'
,p_is_rendered=>'on'
,p_title=>'Date'
,p_format_type=>'date-medium'
,p_format_scaling=>'auto'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
,p_tick_label_rotation=>'auto'
,p_tick_label_position=>'outside'
);
wwv_flow_api.create_jet_chart_axis(
 p_id=>wwv_flow_api.id(26542923132137968219)
,p_chart_id=>wwv_flow_api.id(26542922008878968208)
,p_axis=>'y'
,p_is_rendered=>'on'
,p_title=>'Units'
,p_format_type=>'decimal'
,p_decimal_places=>0
,p_format_scaling=>'none'
,p_scaling=>'linear'
,p_baseline_scaling=>'zero'
,p_position=>'auto'
,p_major_tick_rendered=>'on'
,p_minor_tick_rendered=>'off'
,p_tick_label_rendered=>'on'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(27156729684833850150)
,p_button_sequence=>30
,p_button_name=>'btnnoqty'
,p_button_action=>'REDIRECT_PAGE'
,p_button_template_options=>'#DEFAULT#'
,p_button_template_id=>wwv_flow_api.id(17252253235234312389)
,p_button_image_alt=>'Stores Not Included in This Graph As of Jan 11th'
,p_button_redirect_url=>'f?p=&APP_ID.:15:&SESSION.::&DEBUG.:::'
,p_grid_new_row=>'N'
,p_grid_new_column=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(19126178154816205108)
,p_name=>'P8_TITLE'
,p_item_sequence=>20
,p_prompt=>'Known Store Quantities (ONTARIO)'
,p_display_as=>'NATIVE_TEXT_FIELD'
,p_cSize=>30
,p_colspan=>8
,p_field_template=>wwv_flow_api.id(17252250078138312387)
,p_item_template_options=>'#DEFAULT#'
,p_attribute_01=>'N'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
,p_attribute_04=>'TEXT'
,p_attribute_05=>'BOTH'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(22480255184633454632)
,p_name=>'P8_LIST'
,p_is_required=>true
,p_item_sequence=>50
,p_prompt=>'SELECT DATE RANGE'
,p_display_as=>'NATIVE_SELECT_LIST'
,p_lov=>'STATIC2:Last 7 days;SHOW,Last 30 days;HIDE'
,p_cHeight=>1
,p_field_template=>wwv_flow_api.id(17252250078138312387)
,p_item_icon_css_classes=>'fa-calendar-search'
,p_item_template_options=>'#DEFAULT#'
,p_warn_on_unsaved_changes=>'I'
,p_lov_display_extra=>'YES'
,p_attribute_01=>'NONE'
,p_attribute_02=>'N'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(22480255225819454633)
,p_name=>'Change'
,p_event_sequence=>10
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P8_LIST'
,p_condition_element=>'P8_LIST'
,p_triggering_condition_type=>'EQUALS'
,p_triggering_expression=>'SHOW'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480255327479454634)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064579601272758203)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480255441210454635)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064579601272758203)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26260087341546534228)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>20
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260085885600534213)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480256220412454643)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>30
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064580799294758214)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923541926968223)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>30
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260085885600534213)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480256909909454650)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>40
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064581852447758225)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26260087424470534229)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>40
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260087522733534230)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480256433113454645)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>50
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064581852447758225)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923693360968224)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>50
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260088970208534244)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26260084695491534201)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>60
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064582971203758236)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923231839968220)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>60
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260088970208534244)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923395195968221)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>70
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064582971203758236)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923734345968225)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>70
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26542921968889968207)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(22480256338525454644)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>80
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(19064580799294758214)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923462976968222)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'TRUE'
,p_action_sequence=>80
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_HIDE'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26542921968889968207)
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(26542923823246968226)
,p_event_id=>wwv_flow_api.id(22480255225819454633)
,p_event_result=>'FALSE'
,p_action_sequence=>90
,p_execute_on_page_init=>'Y'
,p_action=>'NATIVE_SHOW'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(26260087522733534230)
);
wwv_flow_api.component_end;
end;
/
